export QW_ENABLE_INGEST_V3=true
export QW_INGEST_WAL_URI=s3://<your-bucket>/ingest-wal
export QW_INGEST_WAL_FLUSH_INTERVAL_MS=${FLUSH_MS:-250}
export QW_INGEST_WAL_FETCH_FALLBACK_GRACE_SECS=10
export QW_INGEST_WAL_GC_MIN_AGE_SECS=60
export RUST_LOG=info
export AWS_REGION=eu-north-1
export QW_INGEST_WAL_FLUSH_NUM_BYTES=${FLUSH_BYTES:-8MiB}
